PCGrad: false
batch_size: 1
cudnn_benchmark_toggle: false
cudnn_deterministic_toggle: true
data_type: partialspoof
dev_flag: false
epochs: 50
eps: 1.0e-08
eval_mode_for_validation: false
grad_clip_norm: -1.0
hidden_feature_selection: all
ignore_optimizer_statistics_in_trained_model: false
ignore_training_history_in_trained_model: false
inference: false
l2_penalty: -1.0
loss_weight: none
loss_weight_hyper: 2.0
lr: 0.0001
lr_decay_factor: -1.0
lr_scheduler_type: 0
model_forward_with_file_name: false
model_forward_with_target: false
module_config: config
module_model: model
multi_branch_fix: ''
multi_gpu_data_parallel: false
multi_scale_active:
- '2'
- '4'
- '8'
- '16'
- '32'
- '64'
- utt
no_best_epochs: 5
no_cuda: false
not_save_each_epoch: false
num_workers: 0
optimizer: Adam
output_dir: ./output
sampler: None
save_epoch_name: epoch
save_model_dir: ./
save_model_ext: .pt
save_output:
- ali
save_trained_name: trained_network
seed: 1
shuffle: true
single_task: false
ssl_finetune: false
task_id: utt
temp_flag: ''
temp_flag_dev: ''
trained_model: ''
uncertainty_weight: false
verbose: 1
way_to_merge_datasets: concatenate
